/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.Article;
import DB.Client;
import DB.Command;
import DB.Command_has_article;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class New_command_form extends javax.swing.JPanel {

        
        //variable for database management 
        private Article a = new Article();
        private Client c = new Client();
        private Command_has_article cha = new Command_has_article();
        private Command com = new Command();
        
        private ArrayList<Article> articles = new ArrayList() ; 
        private ArrayList<Client> clients = new ArrayList();
        
        //private JFrame f = new JFrame();
        
        int montant;
        /**
         * Creates new form New_command_form
         */
        public New_command_form() {
                initComponents();
                this.articles = a.Read_Article();
                this.clients = c.Read_client();
                this.jLabel7.setText(""+com.genere());
                montant = 0;
                
                //jtable 
                this.jTable1.getTableHeader().setFont(new Font("MV Boli",Font.BOLD,12));
                
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox();
                jLabel2 = new javax.swing.JLabel();
                jComboBox2 = new javax.swing.JComboBox();
                jLabel3 = new javax.swing.JLabel();
                jTextFieldQty = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jButtonadd = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jLabel4 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jButtonsave = new javax.swing.JButton();

                setBackground(new java.awt.Color(255, 255, 255));
                addContainerListener(new java.awt.event.ContainerAdapter() {
                        public void componentAdded(java.awt.event.ContainerEvent evt) {
                                formComponentAdded(evt);
                        }
                });

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray), "Command information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MV Boli", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N

                jLabel1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jLabel1.setText("Client Name:");

                jComboBox1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N

                jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jLabel2.setText("Name Article:");

                jComboBox2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jComboBox2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox2ActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jLabel3.setText("Quantity");

                jTextFieldQty.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N

                jButton1.setBackground(new java.awt.Color(255, 0, 51));
                jButton1.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
                jButton1.setForeground(new java.awt.Color(0, 204, 204));
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
                jButton1.setText("clear");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButtonadd.setBackground(new java.awt.Color(0, 153, 153));
                jButtonadd.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
                jButtonadd.setForeground(new java.awt.Color(102, 102, 0));
                jButtonadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sauvegarder.gif"))); // NOI18N
                jButtonadd.setText("Add");
                jButtonadd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonaddActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Total price");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jTextFieldQty)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonadd, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                );

                jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
                jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "Print", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MV Boli", 0, 18), new java.awt.Color(0, 204, 204))); // NOI18N

                jTable1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "N°", "Designation", "unit price", "quantity", "total price"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, true, true, true, true
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jTable1.setRowHeight(20);
                jScrollPane1.setViewportView(jTable1);
                if (jTable1.getColumnModel().getColumnCount() > 0) {
                        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
                        jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
                        jTable1.getColumnModel().getColumn(0).setMaxWidth(35);
                        jTable1.getColumnModel().getColumn(1).setMinWidth(140);
                        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
                        jTable1.getColumnModel().getColumn(1).setMaxWidth(160);
                        jTable1.getColumnModel().getColumn(2).setMinWidth(60);
                        jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
                        jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
                        jTable1.getColumnModel().getColumn(3).setMinWidth(60);
                        jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
                        jTable1.getColumnModel().getColumn(3).setMaxWidth(70);
                        jTable1.getColumnModel().getColumn(4).setMinWidth(70);
                        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
                        jTable1.getColumnModel().getColumn(4).setMaxWidth(90);
                }

                jLabel4.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("CREATE A NEW COMMAND");
                jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

                jLabel6.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setText("command N°");

                jLabel7.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel7.setText("jLabel7");

                jButtonsave.setBackground(new java.awt.Color(0, 153, 153));
                jButtonsave.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
                jButtonsave.setForeground(new java.awt.Color(0, 102, 102));
                jButtonsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sauvegarder.gif"))); // NOI18N
                jButtonsave.setText("Save");
                jButtonsave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonsaveActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(45, 45, 45)
                                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jButtonsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonsave)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
                // TODO add your handling code here:
                
                
                //lecture des clients
                this.articles = a.Read_Article();
                this.jComboBox2.removeAllItems();               

                this.articles.stream().forEach((article) -> {
                        this.jComboBox2.addItem(article.getName());
                });
                
                
                //lecture des articles 
                this.clients = c.Read_client();
                this.jComboBox1.removeAllItems();
                
                this.clients.stream().forEach((cl) -> {
                        this.jComboBox1.addItem(cl.getName());
                });
                System.out.println("on m'a ajouter");
        }//GEN-LAST:event_formComponentAdded

        private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jComboBox2ActionPerformed

        @SuppressWarnings("empty-statement")
        private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
                // TODO add your handling code here:
                int i;
                if (!this.jTextFieldQty.getText().equals("")){ 
                        try{
                                i = Integer.parseInt(this.jTextFieldQty.getText());
                                
                                DefaultTableModel dt = (DefaultTableModel) this.jTable1.getModel();
                                
                                int pt,z = 1;
                                for (Article article : this.articles){
                                       if(article.getName().equals(this.jComboBox2.getSelectedItem().toString())){
                                               
                                               pt = article.getUnitPrice()*i;
                                               this.jLabel5.setText(""+pt);
                                               Object [] obj = {z,article.getName(),article.getUnitPrice(),this.jTextFieldQty.getText(),pt};
                                               z++;
                                               
                                               
                                               //save to the database on the 
                                               cha.SetIdArticle(article.getId());
                                               cha.SetIdCommand(Integer.parseInt(this.jLabel7.getText()));
                                               cha.SetQuantity(Integer.parseInt(this.jTextFieldQty.getText()));
                                               
                                               if (cha.save() == 1){
                                                       System.out.println("Enregistré");
                                                       this.montant += pt;
                                                       this.jTextFieldQty.setText("");
                                                       
                                                       //clear the table
                                                       dt.addRow(obj);
                                               }
                                               break;
                                       }
                                               
                                }
                        }catch(Exception ex){
                                JOptionPane.showMessageDialog(null,ex.getMessage(),"#ERROR 002",JOptionPane.ERROR_MESSAGE);
                        }
                        
                }else
                        JOptionPane.showMessageDialog(null,"Please fill the Quantity","Empty",JOptionPane.ERROR_MESSAGE);
        }//GEN-LAST:event_jButtonaddActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                DefaultTableModel dt = (DefaultTableModel) this.jTable1.getModel();
                this.jLabel5.setText("");
                this.jTextFieldQty.setText("");
                //clear the table
                dt.setRowCount(0);
                
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
                // TODO add your handling code here:

                //save in the database on the table command
                
                DefaultTableModel dt = (DefaultTableModel) this.jTable1.getModel();
                if(dt.getRowCount()!=0){
                        this.com.SetIdCommand(Integer.parseInt(this.jLabel7.getText()));
                        this.clients.stream().forEach((Client cl)->{
                                if(cl.getName().equals(this.jComboBox1.getSelectedItem().toString())){
                                        this.com.SetIdClient(cl.getId());
                                }
                        });
                        this.com.SetMontant(this.montant);

                        if(this.com.save() == 1){
                                System.out.println(" Command save succesfully");
                                JOptionPane.showMessageDialog(null,"Command N° "+this.jLabel7.getText()+""
                                        + "\n Save succesfully ","Save",JOptionPane.INFORMATION_MESSAGE);
                                
                                //clear the table
                                dt.setRowCount(0);
                                
                                
                        }
                }else{
                      JOptionPane.showMessageDialog(null,"your command is empty","Error #011",JOptionPane.ERROR_MESSAGE);  
                }
                
                System.out.println( " je suis dans le save avant le if ");
        }//GEN-LAST:event_jButtonsaveActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButtonadd;
        private javax.swing.JButton jButtonsave;
        private javax.swing.JComboBox jComboBox1;
        private javax.swing.JComboBox jComboBox2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextField jTextFieldQty;
        // End of variables declaration//GEN-END:variables
}
