/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.Client;
import DB.Command;
import javax.swing.*;
import java.awt.Color;
import static java.awt.Color.gray;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.border.*;
/**
 *
 * @author user
 */
public class Print_command extends javax.swing.JPanel {

        /**
         * Creates new form Print_command
         */
        Client cl = new Client();
        Date dt ;
        Command C;
        //Time t;
        public Print_command() {
                initComponents();
        }
        
        public Print_command(Command g) {
             initComponents();
             
             this.C = g;
             
             dt = new Date(C.getCommandDate().getTime());
             DateFormat df = DateFormat.getDateInstance();
             DateFormat tf = DateFormat.getTimeInstance();
             
             String date = df.format(dt);
             String time = tf.format(dt);
             
             this.setBorder(BorderFactory.createTitledBorder(new SoftBevelBorder(BevelBorder.RAISED,gray,gray,gray,gray), 
             date +" "+time,TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BELOW_TOP, 
             new java.awt.Font("MV Boli", 0, 18), new Color(0, 153, 153))); 
             
             this.jLabel1.setText(" "+cl.Read_client(C.getIdClient()).getName()+" "+cl.Read_client(C.getIdClient()).getLocation());
        }
         
         
        // NOI18N


        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();

                setBackground(new java.awt.Color(255, 255, 255));
                setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 255), new java.awt.Color(51, 255, 255), new java.awt.Color(51, 255, 255), new java.awt.Color(51, 255, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MV Boli", 0, 18), new java.awt.Color(102, 255, 102))); // NOI18N

                jLabel1.setFont(new java.awt.Font("MV Boli", 3, 20)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Name_client");

                jButton1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jButton1.setText("Delete");

                jButton2.setBackground(new java.awt.Color(0, 204, 204));
                jButton2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
                jButton2.setForeground(new java.awt.Color(0, 102, 0));
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
                jButton2.setText("Print");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                                                .addComponent(jButton2)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1)))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
              new Print_command_one(this.C).setVisible(true);
                
                
        }//GEN-LAST:event_jButton2ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        // End of variables declaration//GEN-END:variables
}
